inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  Exclude:
    - date_book.gemspec
    - spec/dummy/db/schema.rb
    - spec/dummy/db/migrate/*

Metrics/BlockLength:
  Exclude:
    - config/routes.rb
    - spec/*
    - spec/*/*
    - spec/*/*/*
    - spec/dummy/db/seeds/*

Metrics/ModuleLength:
  Exclude:
    - spec/*
    - spec/*/*
    - spec/*/*/*

Metrics/MethodLength:
  Exclude:
    - db/migrate/*

Style/ClassVars:
  Exclude:
    - 'spec/support/shared_connection.rb'