# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: date_book 0.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "date_book".freeze
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Karen Lundgren".freeze]
  s.date = "2017-07-28"
  s.email = "karen.e.lundgren@gmail.com".freeze
  s.executables = ["rails".freeze]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".rspec",
    ".rubocop.yml",
    ".rubocop_todo.yml",
    ".ruby-gemset",
    ".ruby-version",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "MIT-LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "app/assets/config/gem_template_manifest.js",
    "app/assets/images/gem_template/.keep",
    "app/assets/javascripts/gem_template/application.js",
    "app/assets/stylesheets/gem_template/application.css",
    "app/controllers/gem_template/application_controller.rb",
    "app/helpers/gem_template/application_helper.rb",
    "app/jobs/gem_template/application_job.rb",
    "app/mailers/gem_template/application_mailer.rb",
    "app/models/gem_template/application_record.rb",
    "app/views/layouts/gem_template/application.html.erb",
    "bin/rails",
    "config/routes.rb",
    "date_book.gemspec",
    "lib/date_book.rb",
    "lib/date_book/engine.rb",
    "lib/date_book/version.rb",
    "lib/tasks/date_book_tasks.rake",
    "spec/dummy/Rakefile",
    "spec/dummy/app/assets/config/manifest.js",
    "spec/dummy/app/assets/images/.keep",
    "spec/dummy/app/assets/javascripts/application.js",
    "spec/dummy/app/assets/stylesheets/application.scss",
    "spec/dummy/app/assets/stylesheets/bootstrap-everything.scss",
    "spec/dummy/app/controllers/application_controller.rb",
    "spec/dummy/app/controllers/concerns/.keep",
    "spec/dummy/app/helpers/application_helper.rb",
    "spec/dummy/app/mailers/application_mailer.rb",
    "spec/dummy/app/models/application_record.rb",
    "spec/dummy/app/models/concerns/.keep",
    "spec/dummy/app/views/layouts/application.html.haml",
    "spec/dummy/app/views/pages/index.html.haml",
    "spec/dummy/bin/bundle",
    "spec/dummy/bin/rails",
    "spec/dummy/bin/rake",
    "spec/dummy/bin/setup",
    "spec/dummy/bin/update",
    "spec/dummy/config.ru",
    "spec/dummy/config/application.rb",
    "spec/dummy/config/boot.rb",
    "spec/dummy/config/cable.yml",
    "spec/dummy/config/database.yml",
    "spec/dummy/config/environment.rb",
    "spec/dummy/config/environments/development.rb",
    "spec/dummy/config/environments/test.rb",
    "spec/dummy/config/initializers/application_controller_renderer.rb",
    "spec/dummy/config/initializers/assets.rb",
    "spec/dummy/config/initializers/backtrace_silencers.rb",
    "spec/dummy/config/initializers/cookies_serializer.rb",
    "spec/dummy/config/initializers/filter_parameter_logging.rb",
    "spec/dummy/config/initializers/high_voltage.rb",
    "spec/dummy/config/initializers/inflections.rb",
    "spec/dummy/config/initializers/mime_types.rb",
    "spec/dummy/config/initializers/new_framework_defaults.rb",
    "spec/dummy/config/initializers/session_store.rb",
    "spec/dummy/config/initializers/wrap_parameters.rb",
    "spec/dummy/config/locales/en.yml",
    "spec/dummy/config/puma.rb",
    "spec/dummy/config/routes.rb",
    "spec/dummy/config/secrets.yml",
    "spec/dummy/config/spring.rb",
    "spec/dummy/db/schema.rb",
    "spec/dummy/db/seeds.rb",
    "spec/dummy/lib/assets/.keep",
    "spec/dummy/log/.keep",
    "spec/rails_helper.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://www.gemvein.com/museum/cases/date_book".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.6.11".freeze
  s.summary = "Rails 4 & 5 Engine that does stuff.".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>.freeze, ["< 6", ">= 4"])
      s.add_runtime_dependency(%q<rails-i18n>.freeze, ["< 6", ">= 4"])
      s.add_runtime_dependency(%q<bootstrap_leather>.freeze, ["< 1", ">= 0.9"])
      s.add_runtime_dependency(%q<haml-rails>.freeze, ["< 2", ">= 1.0"])
      s.add_runtime_dependency(%q<jquery-rails>.freeze, ["~> 4"])
      s.add_development_dependency(%q<bundler>.freeze, ["~> 1.0"])
      s.add_development_dependency(%q<juwelier>.freeze, ["~> 2.4"])
      s.add_development_dependency(%q<rubocop>.freeze, [">= 0"])
      s.add_development_dependency(%q<bootstrap-sass>.freeze, ["~> 3.3"])
      s.add_development_dependency(%q<byebug>.freeze, ["~> 9"])
      s.add_development_dependency(%q<factory_girl_rails>.freeze, ["~> 4.5"])
      s.add_development_dependency(%q<faker>.freeze, ["~> 1.4"])
      s.add_development_dependency(%q<rspec-its>.freeze, [">= 1"])
      s.add_development_dependency(%q<rspec-rails>.freeze, ["< 4", ">= 3.5"])
      s.add_development_dependency(%q<seedbank>.freeze, ["~> 0.3"])
      s.add_development_dependency(%q<sqlite3>.freeze, ["~> 1.3"])
      s.add_development_dependency(%q<high_voltage>.freeze, ["~> 3"])
    else
      s.add_dependency(%q<rails>.freeze, ["< 6", ">= 4"])
      s.add_dependency(%q<rails-i18n>.freeze, ["< 6", ">= 4"])
      s.add_dependency(%q<bootstrap_leather>.freeze, ["< 1", ">= 0.9"])
      s.add_dependency(%q<haml-rails>.freeze, ["< 2", ">= 1.0"])
      s.add_dependency(%q<jquery-rails>.freeze, ["~> 4"])
      s.add_dependency(%q<bundler>.freeze, ["~> 1.0"])
      s.add_dependency(%q<juwelier>.freeze, ["~> 2.4"])
      s.add_dependency(%q<rubocop>.freeze, [">= 0"])
      s.add_dependency(%q<bootstrap-sass>.freeze, ["~> 3.3"])
      s.add_dependency(%q<byebug>.freeze, ["~> 9"])
      s.add_dependency(%q<factory_girl_rails>.freeze, ["~> 4.5"])
      s.add_dependency(%q<faker>.freeze, ["~> 1.4"])
      s.add_dependency(%q<rspec-its>.freeze, [">= 1"])
      s.add_dependency(%q<rspec-rails>.freeze, ["< 4", ">= 3.5"])
      s.add_dependency(%q<seedbank>.freeze, ["~> 0.3"])
      s.add_dependency(%q<sqlite3>.freeze, ["~> 1.3"])
      s.add_dependency(%q<high_voltage>.freeze, ["~> 3"])
    end
  else
    s.add_dependency(%q<rails>.freeze, ["< 6", ">= 4"])
    s.add_dependency(%q<rails-i18n>.freeze, ["< 6", ">= 4"])
    s.add_dependency(%q<bootstrap_leather>.freeze, ["< 1", ">= 0.9"])
    s.add_dependency(%q<haml-rails>.freeze, ["< 2", ">= 1.0"])
    s.add_dependency(%q<jquery-rails>.freeze, ["~> 4"])
    s.add_dependency(%q<bundler>.freeze, ["~> 1.0"])
    s.add_dependency(%q<juwelier>.freeze, ["~> 2.4"])
    s.add_dependency(%q<rubocop>.freeze, [">= 0"])
    s.add_dependency(%q<bootstrap-sass>.freeze, ["~> 3.3"])
    s.add_dependency(%q<byebug>.freeze, ["~> 9"])
    s.add_dependency(%q<factory_girl_rails>.freeze, ["~> 4.5"])
    s.add_dependency(%q<faker>.freeze, ["~> 1.4"])
    s.add_dependency(%q<rspec-its>.freeze, [">= 1"])
    s.add_dependency(%q<rspec-rails>.freeze, ["< 4", ">= 3.5"])
    s.add_dependency(%q<seedbank>.freeze, ["~> 0.3"])
    s.add_dependency(%q<sqlite3>.freeze, ["~> 1.3"])
    s.add_dependency(%q<high_voltage>.freeze, ["~> 3"])
  end
end

